version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    image: golang_db-cli:latest
    container_name: golang_db
    ports:
      - "3308:3306"
    tty: true
  app:
    build: 
      context: ./GoBlogs
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    tty: true
    image: goblogs-cli:latest
    container_name: goblogs-cli
    working_dir: /go/src/GoBlogs
    command: go run main.go
    depends_on:
      - db
  web:
    build:
      context: ./AngularClient
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    tty: true
    image: angularclient-cli:latest
    container_name: angularclient-cli
    depends_on:
      - app
   